application: looyload
version: secureable
runtime: python
api_version: 1

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /.*
  script: mirror.py
  secure: optional
